name: Build and Test Kotlin Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Temurin JDK distribution (AdoptOpenJDK)
          java-version: '22'

      # Cache Gradle dependencies to speed up the build
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      # Run Gradle build (with tests)
      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      # Run tests
      - name: Run tests
        run: ./gradlew test --stacktrace
